# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: CI

on:
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0'
          - '1.5'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      
      # "Build"
      - name: Fail on nightly, except on linux
        continue-on-error: ${{ matrix.version == 'nightly' }}
        id: build
        run: |
          if [[ "${{ matrix.version }}" == "nightly" && "${{ matrix.os }}" != "ubuntu-latest" ]]; then
            exit 1
          else
            exit 0
          fi
        shell: bash
      
      - name: Save PR report
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
          echo ${{ steps.build.outcome }} > ./pr/outcome
          echo "Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}" > ./pr/name
        shell: bash
      
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
